version: "3.5"
services:
  class-project:
    build: .
    command: rails s
    ports:
      - target: 3000
        published: 3000
    networks:
      - project-net
    volumes:
      - type: volume
        source: project-vol
        target: /var/www/class-project
networks:
  project-net:
volumes:
  project-vol:






